
# STEP4-4では以下は変更しない
FROM python:3.8-slim-buster
WORKDIR /main
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .
CMD [ "python3","-m","uvicorn", "main:app","--reload", "--host", "0.0.0.0", "--port", "9000"]
